drop table dm_mds.tmp_f_cdr_simplelevratio;
create table dm_mds.tmp_f_cdr_simplelevratio as select *
FROM (
SELECT 
 IDRSSD
,CERT
,CB
,CHARTER_TYPE
,SDI_BK_CLASS_DESC
,SDI_REGAGNT_DESC
,INST_NAME
,INST_STATE
,OCC_ID
,OTS_ID
,TOTAL_BNK_EQUITY_CAPITAL
,TOTAL_ASSETS
,TOTAL_ASSETS_Rcon2170
,OTHR_INTANGIBLES
,GOODWILL
,NET_DEF_TAX_ASST
,TIER1LEVERAGE
,(CASE WHEN (STATE_DESC = 'Texas' AND CHARTER_TYPE ='State-Chartered' AND (SDI_BK_CLASS_DESC = 'SB' OR IDRSSD=623454)) THEN 'Texas SML'
   ELSE STATE_DESC END) AS STATE_DESC
  ,ADJ_TOTAL_BNK_EQ_CAP
  ,ADJ_TOTAL_ASSETS
  ,SIMPLE_LEVERAGE_RATIO
     FROM (
  SELECT /*csv*/
  IDRSSD
  ,CERT
  ,CB
  ,SDI_BK_CLASS_DESC
  ,SDI_REGAGNT_DESC
  ,INST_NAME
  ,INST_STATE
  ,OCC_ID
  ,OTS_ID
  ,STATE_DESC
  ,CASE WHEN (SDI_BK_CLASS_DESC IN ('SM','NM','SB') OR (SDI_BK_CLASS_DESC IN ('SA','OI') AND SDI_REGAGNT_DESC IN ('FDIC','FED'))) THEN 'State-Chartered'
         ELSE 'National Charter' END AS CHARTER_TYPE
  ,TOTAL_BNK_EQUITY_CAPITAL
  ,TOTAL_ASSETS
  ,TOTAL_ASSETS_RCON2170
  ,OTHR_INTANGIBLES
  ,GOODWILL
  ,NET_DEF_TAX_ASST
  ,TIER1LEVERAGE
  ,TOTAL_BNK_EQUITY_CAPITAL - OTHR_INTANGIBLES - GOODWILL - NET_DEF_TAX_ASST AS ADJ_TOTAL_BNK_EQ_CAP
  ,TOTAL_ASSETS - OTHR_INTANGIBLES - GOODWILL - NET_DEF_TAX_ASST AS ADJ_TOTAL_ASSETS
  ,1.0*(TOTAL_BNK_EQUITY_CAPITAL - OTHR_INTANGIBLES - GOODWILL - NET_DEF_TAX_ASST)/(TOTAL_ASSETS - OTHR_INTANGIBLES - GOODWILL - NET_DEF_TAX_ASST) AS SIMPLE_LEVERAGE_RATIO
  FROM (
     SELECT
      A.IDRSSD
      ,A.CERT
      ,A.INST_NAME
      ,A.INST_STATE
      ,A.OCC_ID
      ,A.OTS_ID
      ,CASE WHEN (B.RCFD2148 IS NULL) THEN 0 ELSE B.RCFD2148 END  +  CASE WHEN (B.RCON2148 IS NULL) THEN 0 ELSE B.RCON2148 END AS NET_DEF_TAX_ASST 
      ,CASE WHEN (RCON0426 IS NULL) THEN 0 ELSE RCON0426 END  +  CASE WHEN (RCFD0426 IS NULL) THEN 0 ELSE RCFD0426 END AS OTHR_INTANGIBLES
      ,CASE WHEN (RCFD3163 IS NULL) THEN 0 ELSE RCFD3163 END  +  CASE WHEN (RCON3163 IS NULL) THEN 0 ELSE RCON3163 END AS GOODWILL
      ,CASE WHEN (RCON3210 IS NULL) THEN 0 ELSE RCON3210 END  +  CASE WHEN (RCFD3210 IS NULL) THEN 0 ELSE RCFD3210 END AS TOTAL_BNK_EQUITY_CAPITAL
      ,CASE WHEN (D.RCON3368 IS NULL) THEN 0 ELSE D.RCON3368 END  +  CASE WHEN (D.RCFD3368 IS NULL) THEN 0 ELSE D.RCFD3368 END AS TOTAL_ASSETS
      ,CASE WHEN (RCOA7204 IS NULL) THEN 0 ELSE RCOA7204 END  +  CASE WHEN ( RCFA7204 IS NULL) THEN 0 ELSE  RCFA7204 END AS TIER1LEVERAGE
      ,CASE WHEN (RCON2170 IS NULL) THEN 0 ELSE RCON2170 END + CASE WHEN (RCFD2170 IS NULL) THEN 0 ELSE RCFD2170 END AS TOTAL_ASSETS_RCON2170
      , E.CB
      , F.SDI_BK_CLASS_DESC
      , G.SDI_REGAGNT_DESC
      ,J.STATE_DESC
      FROM DM_ODS.ODS_CDR_POR A
        JOIN DM_ODS.ODS_CDR_RCF B 
           ON A.IDRSSD = B.IDRSSD AND A.QTR=B.QTR
        JOIN DM_ODS.ODS_CDR_RC C
           ON A.IDRSSD = C.IDRSSD AND A.QTR=C.QTR
        JOIN DM_ODS.ODS_CDR_RCK D
           ON A.IDRSSD = D.IDRSSD AND A.QTR=D.QTR
        JOIN DM_MDS.MV_LK_SDI_BANK_DEMO_CRNT E
          ON A.IDRSSD = E.FED_RSSD
        JOIN DM_MDS.LK_SDI_BK_CLASS F ON E.SDI_BK_CLASS_ID = F.SDI_BK_CLASS_ID
        JOIN DM_MDS.LK_SDI_REGAGNT G ON E.SDI_REGAGNT_ID = G.SDI_REGAGNT_ID
        JOIN DM_ODS.ODS_CDR_RCRI H ON A.IDRSSD = H.IDRSSD AND A.QTR=H.QTR
        JOIN DM_MDS.LK_SDI_STATE J ON J.SDI_STATE_ID = E.SDI_STATE_ID
        WHERE A.QTR=12312015 AND E.DATE_TO > '31-MAR-2016')
));




