
SELECT 
AA.*
,BB.DISTRICT_ID
,BB.N_INCUMBENT
,BB.AVG_ACTUAL_SALARY
,BB.MAX_ACTUAL_SALARY
,BB.MAX_BASE_RANGE
,BB.MID_BASE_RANGE
,BB.MIN_ACTUAL_SALARY
,BB.MIN_BASE_RANGE
from (
SELECT * FROM 
(SELECT DISTINCT ACCOUNT_ID FROM F_SALARY_REPORT_COMBI ORDER BY ACCOUNT_ID) A
CROSS JOIN
(SELECT DISTINCT year FROM F_SALARY_REPORT_COMBI ORDER BY year) B
CROSS JOIN 
(SELECT DISTINCT TITLE_ID FROM F_SALARY_REPORT_COMBI ORDER BY TITLE_ID) C
ORDER BY YEAR, ACCOUNT_ID, TITLE_ID) AA
LEFT JOIN F_SALARY_REPORT_COMBI BB ON (AA.ACCOUNT_ID = BB.ACCOUNT_ID AND
    AA.YEAR=BB.YEAR AND AA.TITLE_ID = BB.TITLE_ID)
ORDER BY aa.YEAR, aa.ACCOUNT_ID, aa.TITLE_ID