SELECT /*csv*/
STA.YEAR
, STA.DISTRICT_ID
, STA.STATE
, STA.STATE_ROLE
, STA.N_STA
, STA.MIN_BASE_STA
, STA.MAX_BASE_STA
, STA.MIN_ACTUAL_STA
, STA.MAX_ACTUAL_STA
, STA.AVG_ACTUAL_STA
, STA.AVG_AWARD_STA
, FED.N_FED
, FED.MIN_BASE_FED
, FED.MAX_BASE_FED
, FED.MIN_ACTUAL_FED
, FED.MAX_ACTUAL_FED
, FED.AVG_ACTUAL_FED
, FED.AVG_AWARD_FED
FROM
(SELECT
*
FROM (
SELECT YEAR
, TRIM(SUBSTR(A.QUESTION_LABEL,INSTR(A.QUESTION_LABEL,'--')+2)) AS SALARY
, B.DISTRICT_ID
, B.STATE
, TRIM(SUBSTR(A.QUESTION_LABEL,1,INSTR(A.QUESTION_LABEL,'--')-1)) AS STATE_ROLE
, A.RESPONSE
FROM 
DM_MDS.TMP_PF_ALLYR_SECTIONI A
JOIN LK_AGENCY B ON B.ACCOUNT = A.ACCOUNT
WHERE
TOPIC_TITLE = '9. Salary Ranges'
AND QUESTION_LABEL LIKE '%--%'
AND YEAR in (2015,2016)
)
PIVOT
(
   MAX(RESPONSE)
   FOR SALARY IN (
     'Number of Incumbents' N_STA
   , 'Minimum Base Range' MIN_BASE_STA
   , 'Maximum Base Range' MAX_BASE_STA
   , 'Minimum Actual Salary' MIN_ACTUAL_STA
   , 'Average Actual Salary' AVG_ACTUAL_STA
   , 'Maximum Actual Salary' MAX_ACTUAL_STA
   , 'Average Variable/Bonus/Incentive Compensation Paid per Incumbent' AVG_AWARD_STA
   )
)
WHERE DISTRICT_ID IS NOT NULL
ORDER BY YEAR, STATE) STA
LEFT OUTER JOIN
(SELECT YEAR
, B.DISTRICT_ID
, B.STATE
, C.TITLE STATE_ROLE
, COUNT(A.NAME) N_FED
, ROUND(MIN(A.SALARY),0) MIN_BASE_FED
, ROUND(MAX(A.SALARY),0) MAX_BASE_FED
, ROUND(MIN(A.SALARY + NVL(A.AWARD,0)),0) MIN_ACTUAL_FED
, ROUND(MAX(A.SALARY + NVL(A.AWARD,0)),0) MAX_ACTUAL_FED
, ROUND(AVG(A.SALARY + NVL(A.AWARD,0)),0) AVG_ACTUAL_FED
, ROUND(AVG(A.AWARD),0) AVG_AWARD_FED
FROM (
SELECT YEAR ,
NAME 
, STATE
, JOB
, PLAN_GRADE
, SALARY/1000 SALARY
, AWARD/1000 AWARD
FROM DM_ODS.ODS_SAL_REPORT) A
JOIN DM_MDS.LK_AGENCY B ON UPPER(B.STATE) = UPPER(A.STATE)
RIGHT OUTER JOIN DM_MDS.LK_SALARY_TITLE C ON C.PLAN_GRADE = A.PLAN_GRADE
WHERE A.JOB IN ('Financial Institution Examining'
  , 'Legal Instruments Examining'
  , 'Administrative Officer'
  , 'Financial Analysis'
  , 'Financial Analysis'
  , 'Credit Union Examining'
  , 'Management and Program Analysis'
  , 'Financial Analysis'
  , 'Financial Institution Examining'
  , 'Management and Program Analysis')
GROUP BY A.YEAR, C.TITLE, B.STATE, B.DISTRICT_ID
ORDER BY A.YEAR, B.STATE) FED
ON FED.YEAR = STA.YEAR
AND FED.DISTRICT_ID = STA.DISTRICT_ID
AND UPPER(FED.STATE) = UPPER(STA.STATE)
AND FED.STATE_ROLE = STA.STATE_ROLE
;
