DROP MATERIALIZED VIEW MV_F_PF_AUTOREPORT;
CREATE MATERIALIZED VIEW MV_F_PF_AUTOREPORT AS
(SELECT
E.PROFILE_YEAR_ID
,F.SECTION_TITLE_ID
,F.SECTION_TITLE_DESC
,G.SECTION_LONG_TITLE_DESC
,i.TOPIC_TITLE_ID
,I.TOPIC_TITLE_DESC
,C."GROUP" AS QUESTION_GROUP
,D.ACCOUNT_ID
,D.SHORT_NAME
,D.FULL_NAME
,C.QUESTION_DET_ID
,C.QUESTION_IS_TABLE_ID
,C.QUESTION_ORDER
,C.LABEL_TEXT
--, A.RESPONSE
,J.ANSWER_TYPE_ID
,J.ANSWER_TYPE_DESC
,A.ANSWER_CHECKBOX
,A.ANSWER_CURRENCY
,A.ANSWER_DATE
,A.ANSWER_NUMBER
,A.ANSWER_PERCENT
,A.ANSWER_PICKLIST
,A.ANSWER_TEXT
,A.ANSWER_TEXT_AREA
,A.FOOTNOTE
,C.QUESTION_REPORT_HEADER_ID
,K.QUESTION_REPORT_HEADER_DESC
,c.QUESTION_REPORT_GROUP_ID as salvation

FROM
F_PF_RESPONSE A
JOIN LK_PF_ANSWER B ON B.ANSWER_ID = A.ANSWER_ID
JOIN LK_PF_QUESTION_DET C ON B.QUESTION_DET_ID=C.QUESTION_DET_ID
JOIN LK_PF_ACCOUNT D ON A.ACCOUNT_ID = D.ACCOUNT_ID
JOIN LK_PF_SECTION E ON A.SECTION_ID = E.SECTION_ID
JOIN LK_PF_SECTION_TITLE F ON E.SECTION_TITLE_ID = F.SECTION_TITLE_ID
JOIN LK_PF_SECTION_LONG_TITLE G ON G.SECTION_LONG_TITLE_ID = E.SECTION_LONG_TITLE_ID
JOIN LK_PF_TOPIC H ON A.TOPIC_ID = H.TOPIC_ID
JOIN LK_PF_TOPIC_TITLE I ON H.TOPIC_TITLE_ID = I.TOPIC_TITLE_ID
JOIN LK_PF_ANSWER_TYPE J ON B.ANSWER_TYPE_ID = J.ANSWER_TYPE_ID
join lk_pf_question_report_header k on c.question_report_header_id = k.question_Report_header_id


WHERE
C.QUESTION_IS_ACTIVE_ID = 0
)