SELECT 
A.PROFILE_YEAR__C,
A.SECTION_NAME__C,
A.TOPIC_TITLE__C,
A.ORDER__C,
A.QUESTION_NUMBER__C,
A.LABEL_TEXT__C,
A.ANSWERTYPE__C,
A.PICKLIST_VALUES__C,
A.WIDTH__C
 FROM ODS_PROFILE_QUESTION__C A
 JOIN ODS_PROFILE_TOPIC__C B ON (A.TOPIC__C = B.ID)
WHERE A.PROFILE_YEAR__C = 2015
AND A.SECTION_NAME__C = 'Section I'
AND A.ISACTIVE__C = 1 
--AND A.WIDTH__C IS NOT NULL
AND LABEL_TEXT__C <> 'Blank Label'
ORDER BY A.PROFILE_YEAR__C, A.SECTION_NAME__C, CAST(B.ORDER__C AS NUMBER), A.ORDER__C
