DROP TABLE TMP_PF_ACCREDITATION;
CREATE TABLE TMP_PF_ACCREDITATION AS
SELECT
*
FROM (
SELECT A.YEAR
, A.ACCOUNT
, A.OLSONID
, A.RESPONSE
FROM
TMP_PF_ALLYR_SECTIONI A
WHERE
A.YEAR in ('2012','2013','2014','2015')
)
PIVOT
(
   MAX(RESPONSE)
   FOR OLSONID IN (
     'QMICDT_7971-A' CURRENT_FY_BUDGET
   , 'QMICDT_7984-A' ACTUAL_EXP_PREV_FY
   , 'QMICDT_7974-A' AFFECTED_REORGANIZATION
   , 'QMICDT_7974-A' BUDGET_COMMERCIAL_BK
   , 'RC_5749-A' GENERAL_FUND
   , 'QMICDT_4602-A' EXAM_FEE_SPECIALTY
   , 'QMICDT_4-A' NUM_INSURED_BANKS
   , 'QMICDT_5-A' TOTAL_ASSETS_BANKS
   , 'QMICDT_972-A' NUM_INSURED_SAVINGS_BKS
   , 'QMICDT_973-A' TOTAL_ASSETS_SAVINGS_BKS
   , 'QMICDT_43-A' NONDEPOSIT_TRUST_COMPANIES
   , 'QMICDT_44-A' TOTAL_ASSETS_ND_TRUST
   , 'QMICDT_40-A' INDUSTRIAL_LOAN_COMPANIES
   , 'QMICDT_41-A' TOTAL_ASSETS_IND_LOAN
   , 'QMICDT_7926-A' NUM_OF_4_N_5_RATED_BANKS
   , 'QMICDT_7930-A' NUM_OF_BANK_FAILURES
   , 'QMICDT_1155-A' BSA_EXAMS_INDEPENDENT
   , 'QMICDT_1156-A' BSA_JOINT_EXAMS_FED_RES_FDIC
   , 'QMICDT_1157-A' BSA_CONCURRENT_FED_RES_FDIC
   , 'QMICDT_5768-A' IT_EXAMS_INDEPENDENT 
   , 'QMICDT_5771-A' IT_EXAMS_JOINT
   , 'QMICDT_5774-A' IT_EXAMS_CONCURRENT
   , 'RC_8003-A' PARTICIPATED_ON_TSP_EXAMS
   , 'QMICDT_1163-A' NON_DEP_TR_EXAMS
   , 'QMICDT_1164-A' NON_DEP_TR_EXAMS_TURNAROUND
   , 'SFDC-82660-A' NUM_FIELD_BANK_EXAMINERS
   , 'SFDC-82686-A' Total_IS_Bank_Examiners
   , 'QMICDT_372-A' TOTAL_HOLDING_BANK_EXAMINERS
   , 'SFDC-82689-A' TOTAL_TRUST_BANK_EXAMINERS
   , 'RC_244-A' EXAMINER_TURNOVER
   )
)
ORDER BY ACCOUNT, YEAR desc;

