DROP MATERIALIZED VIEW MV_PF_ACCREDITATION;
CREATE MATERIALIZED VIEW MV_PF_ACCREDITATION AS
SELECT YEAR ,
ACCOUNT ,
ACCR_CATEG ,
QUESTION_LABEL ,
CASE WHEN RESPONSE = 'Yes' THEN '1'
     WHEN RESPONSE = 'No' THEN '0'
     WHEN RESPONSE = 'Independent' THEN '0'
     WHEN RESPONSE = 'Part of a Larger Agency' THEN '1'
     ELSE RESPONSE END RESPONSE
FROM TMP_PF_ACCREDITATION_REPORT
union all
(SELECT YEAR ,
'National' ACCOUNT ,
ACCR_CATEG ,
QUESTION_LABEL ,
TO_CHAR(MAX(NATIONAL_AVG)) RESPONSE
FROM TMP_PF_ACCREDITATION_REPORT
GROUP BY YEAR, ACCR_CATEG, QUESTION_LABEL, 'National')
;
