SELECT /*csv*/
 c.ACCOUNT
,c.ACCR_CATEG
,c.QUESTION_LABEL
,c.RESPONSE_2015
,B.RESPONSE_2014
,a.RESPONSE_2013
,c.AVG_2015
,B.AVG_2014
,a.avg_2013
FROM 

(select 
ACCOUNT
,QUESTION_LABEL
,TO_CHAR(RESPONSE) AS RESPONSE_2015
,NATIONAL_AVG as avg_2015
,ACCR_CATEG
FROM DM_MDS.TMP_PF_ACCREDITATION_REPORT
WHERE YEAR = 2015) C

left JOIN
(select /*csv*/
ACCOUNT
,QUESTION_LABEL
,TO_CHAR(RESPONSE) AS RESPONSE_2014
,NATIONAL_AVG as avg_2014
,ACCR_CATEG
FROM DM_MDS.TMP_PF_ACCREDITATION_REPORT
WHERE YEAR = 2014) B
ON (c.ACCOUNT=B.ACCOUNT AND c.QUESTION_LABEL=B.QUESTION_LABEL AND c.ACCR_CATEG=B.ACCR_CATEG)
left JOIN
(
select 
ACCOUNT
,QUESTION_LABEL
,TO_CHAR(RESPONSE) AS RESPONSE_2013
,NATIONAL_AVG as avg_2013
,ACCR_CATEG
FROM DM_MDS.TMP_PF_ACCREDITATION_REPORT 
WHERE YEAR = 2013) A
ON (A.ACCOUNT=C.ACCOUNT AND A.QUESTION_LABEL=C.QUESTION_LABEL AND A.ACCR_CATEG=C.ACCR_CATEG)
