DROP TABLE DM_MDS.TMP_PF_ALLYR_SECTIONI;
CREATE TABLE DM_MDS.TMP_PF_ALLYR_SECTIONI AS
SELECT 
 ACCOUNT
,YEAR
,TOPIC_TITLE
,REGEXP_REPLACE(QUESTION_LABEL,'<[^>]*>',' ') as QUESTION_LABEL 
,RESPONSE
,ANSWERTYPE
,ANSWER_CHECKBOX
,ANSWER_CURRENCY
,ANSWER_DATE
,ANSWER_NUMBER
,ANSWER_PERCENT
,ANSWER_PICKLIST
,ANSWER_TEXT
,ANSWER_TEXT_AREA
,CERTIFIED
,A.REPORT_HEADER_TEXT
,OLSONID
,C.ISTABLE__C
,dense_rank() over (order by account asc, year desc, cast(b.order__C as integer)*100000+ c.order__c) as q_order
FROM 
DM_ods.ODS_PROFILE_RESPONSE__C A
JOIN DM_ODS.ODS_PROFILE_TOPIC__C B ON (A.TOPIC_TITLE = B.TOPIC_TITLE__C
                 AND A.YEAR = B.PROFILE_YEAR__C)
join dm_ods.ods_profile_question__c c on (a.related_question = C.RECORDID)
WHERE 
 SECTION = 'Section I'
 --AND ANSWERTYPE = 'Number'
 AND (RESPONSE_COUNTER > 0 OR (ANSWERTYPE IN ('Number','Currency','Percent','Checkbox')
    AND ANSWER_NUMBER IS NOT NULL OR A.ANSWER_CURRENCY IS NOT NULL
    OR ANSWER_PERCENT IS NOT NULL OR ANSWER_CHECKBOX IS NOT NULL))
 ORDER BY ACCOUNT ASC, YEAR DESC,  cast(b.order__C as integer), c.order__c;
 
