SELECT /*csv*/
EXTRACT(YEAR FROM A.REPDTE) YEAR
, A.REPDTE
, C.STATE_DESC STATE
, COUNT(DISTINCT B.BANK_DEMO_ID) N_SDI_BANK
, SUM(DISTINCT A.ASSET) SDI_TOTAL_ASSET
FROM 
MV_F_SDI_ACCREDITATION A JOIN
LK_SDI_BANK_DEMO B ON B.BANK_DEMO_ID = A.BANK_DEMO_ID JOIN
LK_SDI_STATE C ON C.SDI_STATE_ID = B.SDI_STATE_ID JOIN
LK_SDI_BK_CLASS D ON D.SDI_BK_CLASS_ID = B.SDI_BK_CLASS_ID JOIN
LK_SDI_REGAGNT E ON E.SDI_REGAGNT_ID = B.SDI_REGAGNT_ID
WHERE
(D.SDI_BK_CLASS_DESC IN ('SM','NM','SB') OR
(D.SDI_BK_CLASS_DESC IN ('OI','SA') AND E.SDI_REGAGNT_DESC IN ('FDIC'))) AND
TO_CHAR(A.REPDTE,'Q') = '4' AND
A.REPDTE > TO_DATE('2013','YYYY')
GROUP BY A.REPDTE, C.STATE_DESC
ORDER BY C.STATE_DESC, A.REPDTE DESC;

/*
SELECT
EXTRACT(YEAR FROM A.REPDTE) YEAR
, A.REPDTE
, C.STATE_DESC STATE
, COUNT (DISTINCT A.CERT) N_SDI_BANK
, SUM(DISTINCT A.ASSET) SDI_TOTAL_ASSET
FROM
DM_ODS.ODS_SDI_ASSETSLIABILITIES A JOIN
DM_ODS.ODS_SDI_BANKDEMOGRAPHICS B ON B.CERT = A.CERT JOIN
DM_MDS.LK_SDI_STATE C ON C.SDI_STATE_DESC = B.STALP
WHERE
(B.BKCLASS IN ('SM','NM','SB') OR
(B.BKCLASS IN ('OI','SA') AND B.REGAGNT IN ('FDIC'))) AND
TO_CHAR(A.REPDTE,'Q') = '4' AND
A.REPDTE > TO_DATE('2013','YYYY')
GROUP BY A.REPDTE, C.STATE_DESC
ORDER BY C.STATE_DESC, A.REPDTE DESC;
*/